export default function Index() {
  return (
    <>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
      <div>index</div>
    </>
  )
}
